### ISSUE TITLE
node/install-packages with Yarn does not use cache

### ISSUE THREAD

**Issue by AlfonsoUceda** [CircleCI-Public/node-orb#95] opened 2021-09-02 07:29 UTC
## Orb version:

circleci/node@4.7.0

## What happened:

This is my configuration for this orb:
```
- node/install-packages:
          pkg-manager: yarn
```
but always the "Installing YARN packages" step install the packages instead of using the cache.

This is the outpout of the "Restoring cache" step:

```
Found a cache from build 28614 at node-deps-arch1-linux-amd64-6_85-v1-update-circle-ci-orbs-5iWF2YzHP8e1G6HhzxszgwKVJ5IrCah37qVy9y7D96U=-pCvIcgffSUKf4AQQJL2DcbU1PjkyP85xag3cObI_gM8=
Size: 32 B
Cached paths:
  * /home/circleci/yarn.lock

Downloading cache archive...
Validating cache...

Unarchiving cache...
```
I've also tried to use `cache-path: ~/project/node_modules` but it didn't work, in fact it wasn't used at all.

Should not the cached path be the following? `  * /home/circleci/project/yarn.lock`

Using the version 2 of this orb (the current one in my project) the cached path used is this one: ` * /home/circleci/project/node_modules`

## Expected behavior:

It should skip installing packages if there is a cache.

**Comment by Jaryt** [comment] 2021-12-08 23:20
looks like a duplicate of #61

**Closed by Jaryt** 2021-12-08 23:20 UTC
Labels: bug, duplicate
