### ISSUE TITLE
Not working with cimg/ruby

### ISSUE THREAD

**Issue by mockdeep** [CircleCI-Public/node-orb#102] opened 2021-11-27 20:16 UTC
## Orb version:

4.7.0

## What happened:

When setting up the build environment on `cimg/ruby:2.7.4-browsers`, this orb fails when checking `npm`. It succeeds in installing `node`:

<details>
  <summary>Install Node.js  14.18.1</summary>

```
#!/bin/bash -eo pipefail
# Only install nvm if it's not already installed
if command -v nvm &> /dev/null; then
    echo "nvm is already installed. Skipping nvm install.";
else
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash;
    echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV;
    echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" --no-use' >> $BASH_ENV;
    source $BASH_ENV;
fi

if [ "$NODE_PARAM_LTS" = "1" ]; then
    nvm install --lts
    nvm alias default lts/*
else
    nvm install "$NODE_PARAM_VERSION"
    nvm alias default "$NODE_PARAM_VERSION"
fi

echo 'nvm use default &>/dev/null' >> $BASH_ENV

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13527  100 13527    0     0  1016k      0 --:--:-- --:--:-- --:--:-- 1016k
=> Downloading nvm from git to '/home/circleci/.nvm'
=> Cloning into '/home/circleci/.nvm'...
Warning: Permanently added the ECDSA host key for IP address '140.82.112.3' to the list of known hosts.
remote: Enumerating objects: 333, done.        
remote: Counting objects: 100% (333/333), done.        
remote: Compressing objects: 100% (283/283), done.        
Receiving objects: 100% (333/333), 177.15 KiB | 8.05 MiB/s, done.
remote: Total 333 (delta 38), reused 150 (delta 25), pack-reused 0        
Resolving deltas: 100% (38/38), done.
=> Compressing and cleaning up git repository

=> Appending nvm source string to /home/circleci/.bashrc
=> Appending bash_completion source string to /home/circleci/.bashrc
=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
Downloading and installing node v14.18.1...
Downloading https://nodejs.org/dist/v14.18.1/node-v14.18.1-linux-x64.tar.xz...
######################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v14.18.1 (npm v6.14.15)
Creating default alias: default -> 14.18.1 (-> v14.18.1 *)
default -> 14.18.1 (-> v14.18.1 *)

CircleCI received exit code 0
```
</details>

But then it fails when setting up NPM:

<details>
  <summary>Install NPM</summary>

```
#!/bin/bash -eo pipefail
if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi

# FUNCTIONS
get_npm_version () {
    if [[ "$NODE_PARAM_NPM_VERSION" == latest ]]; then
    NPM_ORB_VERSION="$(npm view npm | sed -E 's|.*-||g' | grep latest | \
        perl -pe 's/.*: //g' | perl -pe "s/'|,//g")"

    echo "Latest version of NPM is $NPM_ORB_VERSION"
    else
    NPM_ORB_VERSION="$NODE_PARAM_NPM_VERSION"

    echo "Selected version of NPM is $NPM_ORB_VERSION"
    fi
}

installation_check () {
    if command -v npm > /dev/null 2>&1; then
    if npm -v | grep "$NPM_ORB_VERSION" > /dev/null 2>&1; then
        echo "NPM $NPM_ORB_VERSION is already installed"
        exit 0
    fi
    fi
}

get_npm_version
installation_check

if [ "$NODE_PARAM_NPM_VERSION" = latest ]; then
$SUDO npm install -g npm@latest > /dev/null 2>&1 || \
    npm install -g npm@latest > /dev/null 2>&1
else
$SUDO npm install -g "npm@$NPM_ORB_VERSION" > /dev/null 2>&1 || \
    npm install -g "npm@$NPM_ORB_VERSION" > /dev/null 2>&1
fi

# test/verify version
if npm -v | grep "$NPM_ORB_VERSION" > /dev/null 2>&1; then
echo "Success! NPM $(npm -v) has been installed to $(which npm)"
else
echo "Something went wrong; the specified version of NPM could not be installed"
exit 1
fi

Latest version of NPM is 8.1.4
Something went wrong; the specified version of NPM could not be installed

Exited with code exit status 1

CircleCI received exit code 1
```
</details>

## Expected behavior:

It should successfully install NPM.

## Additional Information:

This works fine on the legacy `circleci/ruby:2.7.4-node-browsers` image.

**Comment by Jaryt** [comment] 2021-12-08 02:16
Hi @mockdeep! Thank you for your patience. I was unable to get an error when installing npm with this version of the orb. Are you still facing this issue? If so, can you provide a build link so I can investigate further?

**Comment by mockdeep** [comment] 2021-12-08 05:46
Hi @Jaryt, [here's a repro](https://app.circleci.com/pipelines/github/mockdeep/lmkw/1776/workflows/1a63bd95-d87d-4189-98c9-8f91b63a7223/jobs/1790). I wonder if it somehow conflicts with `install-yarn: true`. When I add `install-npm: false` it works fine.

**Comment by Jaryt** [comment] 2021-12-08 22:25
Did some investigating here and it seems like the root cause is the due to the npm version not getting uninstalled if it does not match with the one passed to it by the orb defaults. Will have a solution in soon!

**Comment by Jaryt** [comment] 2021-12-10 23:24
We've removed the npm installation as it is already installed along with node. If a custom version is needed, that should be added as it's own run command after the node installation. This will be in major version 5 when PR #94 is merged. For now, please add 'install_npm: false' parameter to disable this installation step. Please note that this will be removed once the changes are merged. Thank you!

**Closed by Jaryt** 2021-12-10 23:24 UTC
Labels: bug
