### ISSUE TITLE
Node fails to install on macos

### ISSUE THREAD

**Issue by MasterOdin** [CircleCI-Public/node-orb#65] opened 2020-12-08 22:56 UTC
## Orb version:

This failure was observed using 4.0.1 and 4.1.0. The failure went away under 3.0.1 as that version does not use nvm, so looks like a nvm error. I did not investigate further so as to not waste my mac minutes and that 3.0.1 worked.

## What happened:

```
#!/bin/bash --login -eo pipefail
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
NVM_DIR="$HOME/.nvm"
echo "export NVM_DIR=\"$HOME/.nvm\"" >> $BASH_ENV
echo "[ -s \"$NVM_DIR/nvm.sh\" ] && \. \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV
source $BASH_ENV
nvm install \
 12.13.1  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13527  100 13527    0     0   209k      0 --:--:-- --:--:-- --:--:--  213k
=> Downloading nvm from git to '/Users/distiller/.nvm'
=> Cloning into '/Users/distiller/.nvm'...
remote: Enumerating objects: 290, done.        
remote: Counting objects: 100% (290/290), done.        
remote: Compressing objects: 100% (257/257), done.        
remote: Total 290 (delta 34), reused 110 (delta 20), pack-reused 0        
Receiving objects: 100% (290/290), 163.37 KiB | 4.54 MiB/s, done.
Resolving deltas: 100% (34/34), done.
=> Compressing and cleaning up git repository

=> Appending nvm source string to /Users/distiller/.bashrc
=> Appending bash_completion source string to /Users/distiller/.bashrc
N/A: version "12.13.0 -> N/A" is not yet installed.

You need to run "nvm install 12.13.0" to install it before using it.
=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
N/A: version "12.13.0 -> N/A" is not yet installed.

You need to run "nvm install 12.13.0" to install it before using it.

Exited with code exit status 3
CircleCI received exit code 3
```

## Expected behavior:

Node would be installed, and build would not fail

## Additional Information:

Stripped down build config:
```
version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    macos:
      xcode: '11.4'
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1

    steps:
      - checkout

      - run:
          name: Setup dependencies
          command: brew install unixodbc gnupg coreutils

      - node/install:
          install-yarn: true
          node-version: "12.13.1"

workflows:
  version: 2
  build:
    jobs:
      - build
```

**Comment by KyleTryon** [comment] 2021-01-06 21:50
Thank you for the report @MasterOdin. We will investigate.

**Comment by KyleTryon** [comment] 2021-01-07 21:58
Hello @MasterOdin I have investigated the issue and I am not currently able to replicate it. I am currently working on a new branch and the tests are passing. I specifically tested out your config above, also passing.
https://app.circleci.com/pipelines/github/KyleTryon/CircleCI-Metadata-Build/135/workflows/c78577ab-e68c-4da4-8f4f-855bb59ad754/jobs/357

One difference, I see you have `circleci/node@4.1.1` listed but `4.1.1` does not yet exist so I used `4.1.0`.

Please let me know if I have missed anything. We'll have a Node orb update coming soon but at the moment it wont contain any new features (yet).

**Comment by MasterOdin** [comment] 2021-01-07 22:32
@KyleTryon Thanks for looking into this. The `4.1.1` was a typo on my part (as well as having the pipeline named `build-macos` in one spot and `build` in another as I trimmed down our production config to an example here.

I just re-tried this and I'm hitting the same failure from my OP. Looking at the build logs between the two look essentially the same (with a difference of a number of environment variables that should have no nenv effect) so I'm stumped.

Happy to provide a link to it via email or other means, though probably not directly posting here given it's a private project.

**Comment by KyleTryon** [comment] 2021-01-07 22:50
Thanks @MasterOdin happy to take a look. Would you mind opening a support ticket and referencing this GitHub issue? The support team will reroute the information to me.

https://support.circleci.com/hc/en-us/requests/new

Once the issue is resolved we will respond there and comment what is appropriate here.

**Comment by KyleTryon** [comment] 2021-01-08 15:27
@MasterOdin Thank you, I have taken a look. Would you mind pushing a new commit? I think what may have happened was a temporary network glitch, likely on the side of the nvm repo. My assumption is if you push again the issue will be resolved. Please let us know how it goes.

**Comment by KyleTryon** [comment] 2021-01-13 14:55
Closing as the issue is not replicable or appears to be fixed. Please feel free to respond at any time to re-open this issue.

**Comment by MasterOdin** [comment] 2021-01-14 01:23
I made another commit and it failed in the same way.

**Comment by KyleTryon** [comment] 2021-01-15 16:25
@MasterOdin sorry to bother you for this again, but could I ask you to open a new ticket for this issue with the support team explicitly giving "ssh permission". If it would be alright with you, I would like to SSH into your build and one of mine simultaneously and run a few commands to try and figure out why we may not be able to replicate this.

Just to be extra clear, this will mean that we will SSH into your repository with access to code and the environment, though we would only be using our access to run NVM commands and attempt to resolve this issue. If that is acceptable, please open a ticket giving SSH permissions.

Thank you.

**Comment by MasterOdin** [comment] 2021-01-30 00:11
Sorry for the delay on this, support ticket sent in.

**Comment by KyleTryon** [comment] 2021-02-04 16:24
@MasterOdin We (cc @gmemstr) believe we may have discovered the issue. 

Included in your repository is an `.nvmrc` specifying version `12.13.0`, this is why in the output above in the error you have provided mentions that is attempting to use `12.13.0`, though it has not been specified in the orb.

This is instructing NVM to use `12.13.0`, while looking into this I discovered this project which highlights this issue in their usage example (there is not much out there I could find) https://github.com/nickstanish/nvm-shell-integration#usage

The general consensus online does appear to be that committing your `.nvmrc` file is generally encouraged, or at least should not be damaging.

We will be filing an issue with NVM and possibly a PR. It appears there are provided scripts for automatically installing and using the version in the `.nvmrc` file provided on the nvm repo, but we need this behavior present during the installation as the installer appears to use the version in the `.nvmrc` without first checking if it is installed.

For solutions in the meantime I would recommend either:
  - Not committing the `.nvmrc` file
  - Deleting the file in CircleCI prior to using the node install command (specifying the version in config).

We will respond here with the issue.

**Closed by KyleTryon** 2021-02-04 16:24 UTC
Labels: bug
